window.CUP_SITE_CONFIG = {
  remoteScheduleUrl:
    "https://raw.githubusercontent.com/openfootball/worldcup.json/master/2026/worldcup.json",
  localScheduleUrl: "data/schedule.json",
  refreshIntervalMs: 60000,
  stakePerUnit: 2,
  handicapMap: {
    Qatar: 2,
    Brazil: -1,
    Haiti: 1,
    Australia: 1,
    Germany: -3,
    Netherlands: -1,
    Spain: -2,
    Belgium: -1,
    "Saudi Arabia": 1,
    Iran: -1,
  },
  matchRecommendationBets: [
    {
      id: "mexico-south-africa-score-2-0",
      date: "2026-06-11",
      team1: "Mexico",
      team1Label: "墨西哥",
      team2: "South Africa",
      team2Label: "南非",
      market: "比分",
      selection: "2:0",
      odds: 5.4,
      units: 2,
    },
    {
      id: "mexico-south-africa-score-3-0",
      date: "2026-06-11",
      team1: "Mexico",
      team1Label: "墨西哥",
      team2: "South Africa",
      team2Label: "南非",
      market: "比分",
      selection: "3:0",
      odds: 8,
      units: 2,
    },
    {
      id: "south-korea-czech-score-1-1",
      date: "2026-06-11",
      team1: "South Korea",
      team1Label: "韩国",
      team2: "Czech Republic",
      team2Label: "捷克",
      market: "比分",
      selection: "1:1",
      odds: 5,
      units: 2,
    },
    {
      id: "mexico-win-south-korea-win-parlay",
      market: "2关串关",
      selection: "墨西哥胜 + 韩国胜",
      units: 4,
      legs: [
        {
          date: "2026-06-11",
          team1: "Mexico",
          team1Label: "墨西哥",
          team2: "South Africa",
          team2Label: "南非",
          selection: "墨西哥胜",
          odds: 1.31,
        },
        {
          date: "2026-06-11",
          team1: "South Korea",
          team1Label: "韩国",
          team2: "Czech Republic",
          team2Label: "捷克",
          selection: "韩国胜",
          odds: 2.43,
        },
      ],
    },
    {
      id: "canada-bosnia-draw-win",
      date: "2026-06-12",
      team1: "Canada",
      team1Label: "加拿大",
      team2: "Bosnia & Herzegovina",
      team2Label: "波黑",
      market: "半全场",
      selection: "平胜",
      odds: 4.25,
      units: 1,
    },
    {
      id: "canada-bosnia-draw",
      date: "2026-06-12",
      team1: "Canada",
      team1Label: "加拿大",
      team2: "Bosnia & Herzegovina",
      team2Label: "波黑",
      market: "胜平负",
      selection: "平",
      odds: 3.32,
      units: 1,
    },
    {
      id: "usa-paraguay-draw",
      date: "2026-06-12",
      team1: "USA",
      team1Label: "美国",
      team2: "Paraguay",
      team2Label: "巴拉圭",
      market: "胜平负",
      selection: "平",
      odds: 3.1,
      units: 1,
    },
    {
      id: "usa-paraguay-score-2-1",
      date: "2026-06-12",
      team1: "USA",
      team1Label: "美国",
      team2: "Paraguay",
      team2Label: "巴拉圭",
      market: "比分",
      selection: "2:1",
      odds: 6.6,
      units: 1,
    },
    {
      id: "qatar-switzerland-hcap-draw-haiti-scotland-hcap-away-parlay",
      market: "2关串关",
      selection: "卡塔尔让球平 + 海地让球负",
      units: 2,
      legs: [
        {
          date: "2026-06-13",
          team1: "Qatar",
          team1Label: "卡塔尔",
          team2: "Switzerland",
          team2Label: "瑞士",
          market: "让球胜平负",
          selection: "让球平",
          odds: 3.55,
          requiresHandicap: true,
        },
        {
          date: "2026-06-13",
          team1: "Haiti",
          team1Label: "海地",
          team2: "Scotland",
          team2Label: "苏格兰",
          market: "让球胜平负",
          selection: "让球负",
          odds: 2.15,
          requiresHandicap: true,
        },
      ],
    },
    {
      id: "brazil-morocco-total-2-australia-turkey-hcap-draw-parlay",
      market: "2关串关",
      selection: "巴西vs摩洛哥总进2球 + 澳大利亚让平",
      units: 3,
      legs: [
        {
          date: "2026-06-13",
          team1: "Brazil",
          team1Label: "巴西",
          team2: "Morocco",
          team2Label: "摩洛哥",
          market: "总进球",
          selection: "总进2球",
          odds: 3.1,
        },
        {
          date: "2026-06-13",
          team1: "Australia",
          team1Label: "澳大利亚",
          team2: "Turkey",
          team2Label: "土耳其",
          market: "让球胜平负",
          selection: "让平",
          odds: 3.12,
          requiresHandicap: true,
        },
      ],
    },
    {
      id: "australia-turkey-hcap-draw-brazil-morocco-draw-win-parlay",
      market: "2关串关",
      selection: "澳大利亚让平 + 巴西vs摩洛哥平胜",
      units: 3,
      legs: [
        {
          date: "2026-06-13",
          team1: "Australia",
          team1Label: "澳大利亚",
          team2: "Turkey",
          team2Label: "土耳其",
          market: "让球胜平负",
          selection: "让平",
          odds: 3.12,
          requiresHandicap: true,
        },
        {
          date: "2026-06-13",
          team1: "Brazil",
          team1Label: "巴西",
          team2: "Morocco",
          team2Label: "摩洛哥",
          market: "半全场",
          selection: "平胜",
          odds: 4,
        },
      ],
    },
    {
      id: "brazil-morocco-score-0-1",
      date: "2026-06-13",
      team1: "Brazil",
      team1Label: "巴西",
      team2: "Morocco",
      team2Label: "摩洛哥",
      market: "比分",
      selection: "0:1",
      odds: 12,
      units: 1,
    },
    {
      id: "brazil-win-haiti-lose-parlay",
      market: "2关串关",
      selection: "巴西胜 + 海地负",
      units: 14,
      legs: [
        {
          date: "2026-06-13",
          team1: "Brazil",
          team1Label: "巴西",
          team2: "Morocco",
          team2Label: "摩洛哥",
          market: "胜平负",
          selection: "胜",
          odds: 1.49,
        },
        {
          date: "2026-06-13",
          team1: "Haiti",
          team1Label: "海地",
          team2: "Scotland",
          team2Label: "苏格兰",
          market: "胜平负",
          selection: "负",
          odds: 1.34,
        },
      ],
    },
    {
      id: "brazil-draw-haiti-lose-parlay",
      market: "2关串关",
      selection: "巴西平 + 海地负",
      units: 6,
      legs: [
        {
          date: "2026-06-13",
          team1: "Brazil",
          team1Label: "巴西",
          team2: "Morocco",
          team2Label: "摩洛哥",
          market: "胜平负",
          selection: "平",
          odds: 3.6,
        },
        {
          date: "2026-06-13",
          team1: "Haiti",
          team1Label: "海地",
          team2: "Scotland",
          team2Label: "苏格兰",
          market: "胜平负",
          selection: "负",
          odds: 1.34,
        },
      ],
    },
    {
      id: "brazil-lose-haiti-lose-parlay",
      market: "2关串关",
      selection: "巴西负 + 海地负",
      units: 4,
      legs: [
        {
          date: "2026-06-13",
          team1: "Brazil",
          team1Label: "巴西",
          team2: "Morocco",
          team2Label: "摩洛哥",
          market: "胜平负",
          selection: "负",
          odds: 5.55,
        },
        {
          date: "2026-06-13",
          team1: "Haiti",
          team1Label: "海地",
          team2: "Scotland",
          team2Label: "苏格兰",
          market: "胜平负",
          selection: "负",
          odds: 1.34,
        },
      ],
    },
    {
      id: "australia-turkey-win",
      date: "2026-06-13",
      team1: "Australia",
      team1Label: "澳大利亚",
      team2: "Turkey",
      team2Label: "土耳其",
      market: "胜平负",
      selection: "胜",
      odds: 5.55,
      units: 1,
    },
    {
      id: "germany-curacao-total-4",
      date: "2026-06-14",
      team1: "Germany",
      team1Label: "德国",
      team2: "Curaçao",
      team2Label: "库拉索",
      market: "总进球",
      selection: "总进4球",
      odds: 3.85,
      units: 2,
    },
    {
      id: "netherlands-japan-total-2",
      date: "2026-06-14",
      team1: "Netherlands",
      team1Label: "荷兰",
      team2: "Japan",
      team2Label: "日本",
      market: "总进球",
      selection: "总进2球",
      odds: 3.05,
      units: 3,
    },
    {
      id: "germany-curacao-hcap-draw-netherlands-japan-hcap-away-parlay",
      market: "2关串关",
      selection: "德国让球平 + 荷兰让球负",
      units: 2,
      legs: [
        {
          date: "2026-06-14",
          team1: "Germany",
          team1Label: "德国",
          team2: "Curaçao",
          team2Label: "库拉索",
          market: "让球胜平负",
          selection: "让球平",
          odds: 4.85,
          requiresHandicap: true,
        },
        {
          date: "2026-06-14",
          team1: "Netherlands",
          team1Label: "荷兰",
          team2: "Japan",
          team2Label: "日本",
          market: "让球胜平负",
          selection: "让球负",
          odds: 1.71,
          requiresHandicap: true,
        },
      ],
    },
    {
      id: "netherlands-japan-draw-draw",
      date: "2026-06-14",
      team1: "Netherlands",
      team1Label: "荷兰",
      team2: "Japan",
      team2Label: "日本",
      market: "半全场",
      selection: "平平",
      odds: 5.3,
      units: 1,
    },
    {
      id: "netherlands-japan-total-3",
      date: "2026-06-14",
      team1: "Netherlands",
      team1Label: "荷兰",
      team2: "Japan",
      team2Label: "日本",
      market: "总进球",
      selection: "总进3球",
      odds: 3.2,
      units: 1,
    },
    {
      id: "germany-curacao-score-3-0",
      date: "2026-06-14",
      team1: "Germany",
      team1Label: "德国",
      team2: "Curaçao",
      team2Label: "库拉索",
      market: "比分",
      selection: "3:0",
      odds: 4.9,
      units: 1,
    },
    {
      id: "iran-new-zealand-score-1-0",
      date: "2026-06-15",
      team1: "Iran",
      team1Label: "伊朗",
      team2: "New Zealand",
      team2Label: "新西兰",
      market: "比分",
      selection: "1:0",
      odds: 5.1,
      units: 2,
    },
    {
      id: "iran-new-zealand-total-2",
      date: "2026-06-15",
      team1: "Iran",
      team1Label: "伊朗",
      team2: "New Zealand",
      team2Label: "新西兰",
      market: "总进球",
      selection: "总进2球",
      odds: 3.1,
      units: 1,
    },
    {
      id: "iran-new-zealand-score-1-1",
      date: "2026-06-15",
      team1: "Iran",
      team1Label: "伊朗",
      team2: "New Zealand",
      team2Label: "新西兰",
      market: "比分",
      selection: "1:1",
      odds: 5.8,
      units: 1,
    },
    {
      id: "saudi-arabia-uruguay-total-3",
      date: "2026-06-15",
      team1: "Saudi Arabia",
      team1Label: "沙特",
      team2: "Uruguay",
      team2Label: "乌拉圭",
      market: "总进球",
      selection: "总进3球",
      odds: 3.4,
      units: 1,
    },
    {
      id: "saudi-arabia-uruguay-score-0-2",
      date: "2026-06-15",
      team1: "Saudi Arabia",
      team1Label: "沙特",
      team2: "Uruguay",
      team2Label: "乌拉圭",
      market: "比分",
      selection: "0:2",
      odds: 5,
      units: 1,
    },
    {
      id: "saudi-arabia-uruguay-draw-lose",
      date: "2026-06-15",
      team1: "Saudi Arabia",
      team1Label: "沙特",
      team2: "Uruguay",
      team2Label: "乌拉圭",
      market: "半全场",
      selection: "平负",
      odds: 3.6,
      units: 3,
    },
    {
      id: "belgium-egypt-score-2-1",
      date: "2026-06-15",
      team1: "Belgium",
      team1Label: "比利时",
      team2: "Egypt",
      team2Label: "埃及",
      market: "比分",
      selection: "2:1",
      odds: 5.8,
      units: 1,
    },
    {
      id: "belgium-egypt-score-1-1",
      date: "2026-06-15",
      team1: "Belgium",
      team1Label: "比利时",
      team2: "Egypt",
      team2Label: "埃及",
      market: "比分",
      selection: "1:1",
      odds: 6.7,
      units: 1,
    },
    {
      id: "belgium-egypt-total-2",
      date: "2026-06-15",
      team1: "Belgium",
      team1Label: "比利时",
      team2: "Egypt",
      team2Label: "埃及",
      market: "总进球",
      selection: "总进2球",
      odds: 3.3,
      units: 3,
    },
    {
      id: "spain-cape-verde-win-other",
      date: "2026-06-15",
      team1: "Spain",
      team1Label: "西班牙",
      team2: "Cape Verde",
      team2Label: "佛得角",
      market: "比分",
      selection: "胜其它",
      odds: 5.75,
      units: 1,
    },
    {
      id: "spain-cape-verde-score-3-0",
      date: "2026-06-15",
      team1: "Spain",
      team1Label: "西班牙",
      team2: "Cape Verde",
      team2Label: "佛得角",
      market: "比分",
      selection: "3:0",
      odds: 4.75,
      units: 1,
    },
    {
      id: "spain-cape-verde-total-4",
      date: "2026-06-15",
      team1: "Spain",
      team1Label: "西班牙",
      team2: "Cape Verde",
      team2Label: "佛得角",
      market: "总进球",
      selection: "总进4球",
      odds: 4.1,
      units: 3,
    },
    {
      id: "belgium-egypt-total-2-saudi-arabia-uruguay-draw-lose-parlay",
      market: "2关串关",
      selection: "比利时vs埃及总进2球 + 沙特vs乌拉圭平负",
      units: 1,
      legs: [
        {
          date: "2026-06-15",
          team1: "Belgium",
          team1Label: "比利时",
          team2: "Egypt",
          team2Label: "埃及",
          market: "总进球",
          selection: "总进2球",
          odds: 3.4,
        },
        {
          date: "2026-06-15",
          team1: "Saudi Arabia",
          team1Label: "沙特",
          team2: "Uruguay",
          team2Label: "乌拉圭",
          market: "半全场",
          selection: "平负",
          odds: 3.6,
        },
      ],
    },
    {
      id: "spain-cape-verde-total-4-saudi-arabia-uruguay-draw-lose-parlay",
      market: "2关串关",
      selection: "西班牙vs佛得角总进4球 + 沙特vs乌拉圭平负",
      units: 2,
      legs: [
        {
          date: "2026-06-15",
          team1: "Spain",
          team1Label: "西班牙",
          team2: "Cape Verde",
          team2Label: "佛得角",
          market: "总进球",
          selection: "总进4球",
          odds: 4.1,
        },
        {
          date: "2026-06-15",
          team1: "Saudi Arabia",
          team1Label: "沙特",
          team2: "Uruguay",
          team2Label: "乌拉圭",
          market: "半全场",
          selection: "平负",
          odds: 3.6,
        },
      ],
    },
    {
      id: "spain-cape-verde-win-other-saudi-arabia-uruguay-score-0-2-parlay",
      market: "2关串关",
      selection: "西班牙胜其它 + 沙特vs乌拉圭0:2",
      units: 1,
      legs: [
        {
          date: "2026-06-15",
          team1: "Spain",
          team1Label: "西班牙",
          team2: "Cape Verde",
          team2Label: "佛得角",
          market: "比分",
          selection: "胜其它",
          odds: 5.75,
        },
        {
          date: "2026-06-15",
          team1: "Saudi Arabia",
          team1Label: "沙特",
          team2: "Uruguay",
          team2Label: "乌拉圭",
          market: "比分",
          selection: "0:2",
          odds: 5,
        },
      ],
    },
    {
      id: "belgium-egypt-total-2-iran-new-zealand-total-2-parlay",
      market: "2关串关",
      selection: "比利时vs埃及总进2球 + 伊朗vs新西兰总进2球",
      units: 2,
      legs: [
        {
          date: "2026-06-15",
          team1: "Belgium",
          team1Label: "比利时",
          team2: "Egypt",
          team2Label: "埃及",
          market: "总进球",
          selection: "总进2球",
          odds: 3.3,
        },
        {
          date: "2026-06-15",
          team1: "Iran",
          team1Label: "伊朗",
          team2: "New Zealand",
          team2Label: "新西兰",
          market: "总进球",
          selection: "总进2球",
          odds: 3.1,
        },
      ],
    },
  ],
  championBets: [
    {
      id: "spain-norway",
      champion: "Spain",
      championLabel: "西班牙",
      runnerUp: "Norway",
      runnerUpLabel: "挪威",
      odds: 75,
      units: 1,
    },
    {
      id: "france-norway",
      champion: "France",
      championLabel: "法国",
      runnerUp: "Norway",
      runnerUpLabel: "挪威",
      odds: 65,
      units: 1,
    },
    {
      id: "argentina-norway",
      champion: "Argentina",
      championLabel: "阿根廷",
      runnerUp: "Norway",
      runnerUpLabel: "挪威",
      odds: 150,
      units: 1,
    },
    {
      id: "other-combinations",
      champion: "其他",
      championLabel: "其他",
      runnerUp: "其他",
      runnerUpLabel: "其他",
      odds: 3,
      units: 2,
    },
  ],
  flagCodeMap: {
    Algeria: "dz",
    Argentina: "ar",
    Australia: "au",
    Austria: "at",
    Belgium: "be",
    "Bosnia & Herzegovina": "ba",
    Brazil: "br",
    Canada: "ca",
    "Cape Verde": "cv",
    Colombia: "co",
    Croatia: "hr",
    Curaçao: "cw",
    "Czech Republic": "cz",
    "DR Congo": "cd",
    Ecuador: "ec",
    Egypt: "eg",
    England: "gb-eng",
    France: "fr",
    Germany: "de",
    Ghana: "gh",
    Haiti: "ht",
    Iran: "ir",
    Iraq: "iq",
    "Ivory Coast": "ci",
    Japan: "jp",
    Jordan: "jo",
    Mexico: "mx",
    Morocco: "ma",
    Netherlands: "nl",
    "New Zealand": "nz",
    Norway: "no",
    Panama: "pa",
    Paraguay: "py",
    Portugal: "pt",
    Qatar: "qa",
    "Saudi Arabia": "sa",
    Scotland: "gb-sct",
    Senegal: "sn",
    "South Africa": "za",
    "South Korea": "kr",
    Spain: "es",
    Sweden: "se",
    Switzerland: "ch",
    Tunisia: "tn",
    Turkey: "tr",
    USA: "us",
    Uruguay: "uy",
    Uzbekistan: "uz",
  },
  flagMap: {
    Algeria: "🇩🇿",
    Argentina: "🇦🇷",
    Australia: "🇦🇺",
    Austria: "🇦🇹",
    Belgium: "🇧🇪",
    "Bosnia & Herzegovina": "🇧🇦",
    Brazil: "🇧🇷",
    Canada: "🇨🇦",
    "Cape Verde": "🇨🇻",
    Colombia: "🇨🇴",
    Croatia: "🇭🇷",
    Curaçao: "🇨🇼",
    "Czech Republic": "🇨🇿",
    Denmark: "🇩🇰",
    "DR Congo": "🇨🇩",
    Ecuador: "🇪🇨",
    Egypt: "🇪🇬",
    England: "🏴",
    France: "🇫🇷",
    Germany: "🇩🇪",
    Ghana: "🇬🇭",
    Haiti: "🇭🇹",
    Iran: "🇮🇷",
    Iraq: "🇮🇶",
    Italy: "🇮🇹",
    "Ivory Coast": "🇨🇮",
    Japan: "🇯🇵",
    Jordan: "🇯🇴",
    Mexico: "🇲🇽",
    Morocco: "🇲🇦",
    Netherlands: "🇳🇱",
    "New Zealand": "🇳🇿",
    Norway: "🇳🇴",
    Panama: "🇵🇦",
    Paraguay: "🇵🇾",
    Portugal: "🇵🇹",
    Qatar: "🇶🇦",
    Scotland: "🏴",
    Senegal: "🇸🇳",
    "Saudi Arabia": "🇸🇦",
    "South Africa": "🇿🇦",
    "South Korea": "🇰🇷",
    Spain: "🇪🇸",
    Sweden: "🇸🇪",
    Switzerland: "🇨🇭",
    Tunisia: "🇹🇳",
    Turkiye: "🇹🇷",
    Turkey: "🇹🇷",
    Uruguay: "🇺🇾",
    USA: "🇺🇸",
    "United States": "🇺🇸",
    Uzbekistan: "🇺🇿",
  },
};
