window.CUP_SITE_CONFIG = {
  remoteScheduleUrl:
    "https://raw.githubusercontent.com/openfootball/worldcup.json/master/2026/worldcup.json",
  localScheduleUrl: "data/schedule.json",
  refreshIntervalMs: 60000,
  matchRecommendationBets: [],
  championBets: [
    {
      id: "spain-norway",
      champion: "Spain",
      championLabel: "西班牙",
      runnerUp: "Norway",
      runnerUpLabel: "挪威",
      units: 1,
    },
    {
      id: "france-norway",
      champion: "France",
      championLabel: "法国",
      runnerUp: "Norway",
      runnerUpLabel: "挪威",
      units: 1,
    },
    {
      id: "argentina-norway",
      champion: "Argentina",
      championLabel: "阿根廷",
      runnerUp: "Norway",
      runnerUpLabel: "挪威",
      units: 1,
    },
    {
      id: "other-combinations",
      champion: "其他",
      championLabel: "其他",
      runnerUp: "其他",
      runnerUpLabel: "其他",
      units: 2,
    },
  ],
  flagCodeMap: {
    Algeria: "dz",
    Argentina: "ar",
    Australia: "au",
    Austria: "at",
    Belgium: "be",
    "Bosnia & Herzegovina": "ba",
    Brazil: "br",
    Canada: "ca",
    "Cape Verde": "cv",
    Colombia: "co",
    Croatia: "hr",
    Curaçao: "cw",
    "Czech Republic": "cz",
    "DR Congo": "cd",
    Ecuador: "ec",
    Egypt: "eg",
    England: "gb-eng",
    France: "fr",
    Germany: "de",
    Ghana: "gh",
    Haiti: "ht",
    Iran: "ir",
    Iraq: "iq",
    "Ivory Coast": "ci",
    Japan: "jp",
    Jordan: "jo",
    Mexico: "mx",
    Morocco: "ma",
    Netherlands: "nl",
    "New Zealand": "nz",
    Norway: "no",
    Panama: "pa",
    Paraguay: "py",
    Portugal: "pt",
    Qatar: "qa",
    "Saudi Arabia": "sa",
    Scotland: "gb-sct",
    Senegal: "sn",
    "South Africa": "za",
    "South Korea": "kr",
    Spain: "es",
    Sweden: "se",
    Switzerland: "ch",
    Tunisia: "tn",
    Turkey: "tr",
    USA: "us",
    Uruguay: "uy",
    Uzbekistan: "uz",
  },
  flagMap: {
    Algeria: "🇩🇿",
    Argentina: "🇦🇷",
    Australia: "🇦🇺",
    Austria: "🇦🇹",
    Belgium: "🇧🇪",
    "Bosnia & Herzegovina": "🇧🇦",
    Brazil: "🇧🇷",
    Canada: "🇨🇦",
    "Cape Verde": "🇨🇻",
    Colombia: "🇨🇴",
    Croatia: "🇭🇷",
    Curaçao: "🇨🇼",
    "Czech Republic": "🇨🇿",
    Denmark: "🇩🇰",
    "DR Congo": "🇨🇩",
    Ecuador: "🇪🇨",
    Egypt: "🇪🇬",
    England: "🏴",
    France: "🇫🇷",
    Germany: "🇩🇪",
    Ghana: "🇬🇭",
    Haiti: "🇭🇹",
    Iran: "🇮🇷",
    Iraq: "🇮🇶",
    Italy: "🇮🇹",
    "Ivory Coast": "🇨🇮",
    Japan: "🇯🇵",
    Jordan: "🇯🇴",
    Mexico: "🇲🇽",
    Morocco: "🇲🇦",
    Netherlands: "🇳🇱",
    "New Zealand": "🇳🇿",
    Norway: "🇳🇴",
    Panama: "🇵🇦",
    Paraguay: "🇵🇾",
    Portugal: "🇵🇹",
    Qatar: "🇶🇦",
    Scotland: "🏴",
    Senegal: "🇸🇳",
    "Saudi Arabia": "🇸🇦",
    "South Africa": "🇿🇦",
    "South Korea": "🇰🇷",
    Spain: "🇪🇸",
    Sweden: "🇸🇪",
    Switzerland: "🇨🇭",
    Tunisia: "🇹🇳",
    Turkiye: "🇹🇷",
    Turkey: "🇹🇷",
    Uruguay: "🇺🇾",
    USA: "🇺🇸",
    "United States": "🇺🇸",
    Uzbekistan: "🇺🇿",
  },
};
