window.CUP_SITE_CONFIG = {
  remoteScheduleUrl:
    "https://raw.githubusercontent.com/openfootball/worldcup.json/master/2026/worldcup.json",
  localScheduleUrl: "data/schedule.json",
  refreshIntervalMs: 60000,
  stakePerUnit: 2,
  matchRecommendationBets: [
    {
      id: "mexico-south-africa-score-2-0",
      date: "2026-06-11",
      team1: "Mexico",
      team1Label: "墨西哥",
      team2: "South Africa",
      team2Label: "南非",
      market: "比分",
      selection: "2:0",
      odds: 5.4,
      units: 2,
    },
    {
      id: "mexico-south-africa-score-3-0",
      date: "2026-06-11",
      team1: "Mexico",
      team1Label: "墨西哥",
      team2: "South Africa",
      team2Label: "南非",
      market: "比分",
      selection: "3:0",
      odds: 8,
      units: 2,
    },
    {
      id: "south-korea-czech-score-1-1",
      date: "2026-06-11",
      team1: "South Korea",
      team1Label: "韩国",
      team2: "Czech Republic",
      team2Label: "捷克",
      market: "比分",
      selection: "1:1",
      odds: 5,
      units: 2,
    },
    {
      id: "mexico-win-south-korea-win-parlay",
      market: "2关串关",
      selection: "墨西哥胜 + 韩国胜",
      units: 4,
      legs: [
        {
          date: "2026-06-11",
          team1: "Mexico",
          team1Label: "墨西哥",
          team2: "South Africa",
          team2Label: "南非",
          selection: "墨西哥胜",
          odds: 1.31,
        },
        {
          date: "2026-06-11",
          team1: "South Korea",
          team1Label: "韩国",
          team2: "Czech Republic",
          team2Label: "捷克",
          selection: "韩国胜",
          odds: 2.43,
        },
      ],
    },
    {
      id: "canada-bosnia-draw-win",
      date: "2026-06-12",
      team1: "Canada",
      team1Label: "加拿大",
      team2: "Bosnia & Herzegovina",
      team2Label: "波黑",
      market: "半全场",
      selection: "平胜",
      odds: 4.25,
      units: 1,
    },
    {
      id: "canada-bosnia-draw",
      date: "2026-06-12",
      team1: "Canada",
      team1Label: "加拿大",
      team2: "Bosnia & Herzegovina",
      team2Label: "波黑",
      market: "胜平负",
      selection: "平",
      odds: 3.32,
      units: 1,
    },
    {
      id: "usa-paraguay-draw",
      date: "2026-06-12",
      team1: "USA",
      team1Label: "美国",
      team2: "Paraguay",
      team2Label: "巴拉圭",
      market: "胜平负",
      selection: "平",
      odds: 3.1,
      units: 1,
    },
    {
      id: "usa-paraguay-score-2-1",
      date: "2026-06-12",
      team1: "USA",
      team1Label: "美国",
      team2: "Paraguay",
      team2Label: "巴拉圭",
      market: "比分",
      selection: "2:1",
      odds: 6.6,
      units: 1,
    },
  ],
  championBets: [
    {
      id: "spain-norway",
      champion: "Spain",
      championLabel: "西班牙",
      runnerUp: "Norway",
      runnerUpLabel: "挪威",
      odds: 75,
      units: 1,
    },
    {
      id: "france-norway",
      champion: "France",
      championLabel: "法国",
      runnerUp: "Norway",
      runnerUpLabel: "挪威",
      odds: 65,
      units: 1,
    },
    {
      id: "argentina-norway",
      champion: "Argentina",
      championLabel: "阿根廷",
      runnerUp: "Norway",
      runnerUpLabel: "挪威",
      odds: 150,
      units: 1,
    },
    {
      id: "other-combinations",
      champion: "其他",
      championLabel: "其他",
      runnerUp: "其他",
      runnerUpLabel: "其他",
      odds: 3,
      units: 2,
    },
  ],
  flagCodeMap: {
    Algeria: "dz",
    Argentina: "ar",
    Australia: "au",
    Austria: "at",
    Belgium: "be",
    "Bosnia & Herzegovina": "ba",
    Brazil: "br",
    Canada: "ca",
    "Cape Verde": "cv",
    Colombia: "co",
    Croatia: "hr",
    Curaçao: "cw",
    "Czech Republic": "cz",
    "DR Congo": "cd",
    Ecuador: "ec",
    Egypt: "eg",
    England: "gb-eng",
    France: "fr",
    Germany: "de",
    Ghana: "gh",
    Haiti: "ht",
    Iran: "ir",
    Iraq: "iq",
    "Ivory Coast": "ci",
    Japan: "jp",
    Jordan: "jo",
    Mexico: "mx",
    Morocco: "ma",
    Netherlands: "nl",
    "New Zealand": "nz",
    Norway: "no",
    Panama: "pa",
    Paraguay: "py",
    Portugal: "pt",
    Qatar: "qa",
    "Saudi Arabia": "sa",
    Scotland: "gb-sct",
    Senegal: "sn",
    "South Africa": "za",
    "South Korea": "kr",
    Spain: "es",
    Sweden: "se",
    Switzerland: "ch",
    Tunisia: "tn",
    Turkey: "tr",
    USA: "us",
    Uruguay: "uy",
    Uzbekistan: "uz",
  },
  flagMap: {
    Algeria: "🇩🇿",
    Argentina: "🇦🇷",
    Australia: "🇦🇺",
    Austria: "🇦🇹",
    Belgium: "🇧🇪",
    "Bosnia & Herzegovina": "🇧🇦",
    Brazil: "🇧🇷",
    Canada: "🇨🇦",
    "Cape Verde": "🇨🇻",
    Colombia: "🇨🇴",
    Croatia: "🇭🇷",
    Curaçao: "🇨🇼",
    "Czech Republic": "🇨🇿",
    Denmark: "🇩🇰",
    "DR Congo": "🇨🇩",
    Ecuador: "🇪🇨",
    Egypt: "🇪🇬",
    England: "🏴",
    France: "🇫🇷",
    Germany: "🇩🇪",
    Ghana: "🇬🇭",
    Haiti: "🇭🇹",
    Iran: "🇮🇷",
    Iraq: "🇮🇶",
    Italy: "🇮🇹",
    "Ivory Coast": "🇨🇮",
    Japan: "🇯🇵",
    Jordan: "🇯🇴",
    Mexico: "🇲🇽",
    Morocco: "🇲🇦",
    Netherlands: "🇳🇱",
    "New Zealand": "🇳🇿",
    Norway: "🇳🇴",
    Panama: "🇵🇦",
    Paraguay: "🇵🇾",
    Portugal: "🇵🇹",
    Qatar: "🇶🇦",
    Scotland: "🏴",
    Senegal: "🇸🇳",
    "Saudi Arabia": "🇸🇦",
    "South Africa": "🇿🇦",
    "South Korea": "🇰🇷",
    Spain: "🇪🇸",
    Sweden: "🇸🇪",
    Switzerland: "🇨🇭",
    Tunisia: "🇹🇳",
    Turkiye: "🇹🇷",
    Turkey: "🇹🇷",
    Uruguay: "🇺🇾",
    USA: "🇺🇸",
    "United States": "🇺🇸",
    Uzbekistan: "🇺🇿",
  },
};
